### ISSUE TITLE
Item Management in Software

### ISSUE THREAD

**Issue by harigyan** [MishraAarambh/mahalaxmi#1]
To manage data of items in the software, implement following points : 

Navigation Menu in Header
1. Add Item 
2. Find Item
3. Stock Entry
4. Stock Reports
5. Print Bar Codes 

Add Item
------------------
To enter data of new item/article into the system, user can use this option. 

Following are the fields of the form to be entered to add new item : 

- itemCode [should be entered by user]
- itemName  [optional]
- rateCode [in format of VINOD KUMAR]
- price
- description
- image
### Additional DB Table columns 
---------------------------------
- id [auto increment]
- addedOn [current timestamp]
- addedBy [Current User ID]

Note : Item entry form may be loaded into the dialog(bootstrap modal) using '+' icon from the item list. 

List Items / Find Item 
-------------------------------
A page to show the list of items. A form in top of list to find/search items by code/name etc. 

S. No. |  Item Code | Item Name | Rate Code | Price | Description 
-------|------------|------------|-----------|-------|-------------
1 |  | | | | 
2 |  | | | | 

Pagination required to show the list of items/articles. 

Edit option should be given with item record. Open edit options in dialog box.

**Comment by MishraAarambh** [comment]
@harigyan 
Part done :-
Written the code for adding the item in the database

Part left :-
Write the code for listing the item in the database, provide capability to search
Have to add the capability to add the image to the item.

**Comment by harigyan** [comment]
When trying to open "Add Item" dialog showing error message : 
`Error: [$injector:unpr] http://errors.angularjs.org/1.5.5/$injector/unpr?p0=ItemServiceProvider%20%3C-%20ItemService
    at http://localhost:8080/angular/angular.min.js:6:412
    at http://localhost:8080/angular/angular.min.js:43:84
    at Object.d [as get] (http://localhost:8080/angular/angular.min.js:40:344)
    at http://localhost:8080/angular/angular.min.js:43:146
    at d (http://localhost:8080/angular/angular.min.js:40:344)
    at e (http://localhost:8080/angular/angular.min.js:41:78)
    at Object.instantiate (http://localhost:8080/angular/angular.min.js:41:441)
    at http://localhost:8080/angular/angular.min.js:89:309
    at link (http://localhost:8080/angular/angular-route.min.js:7:274)
    at ja (http://localhost:8080/angular/angular.min.js:80:350) <div ng-view="" class="ng-scope" data-ng-animate="1">
(anonymous) @ angular.min.js:117
(anonymous) @ angular.min.js:89
ja @ angular.min.js:80
n @ angular.min.js:66
g @ angular.min.js:58
(anonymous) @ angular.min.js:57
(anonymous) @ angular.min.js:62
d @ angular.min.js:59
l @ angular.min.js:63
x @ angular-route.min.js:6
$broadcast @ angular.min.js:147
(anonymous) @ angular-route.min.js:11
(anonymous) @ angular.min.js:130
$eval @ angular.min.js:144
$digest @ angular.min.js:142
$apply @ angular.min.js:145
(anonymous) @ angular.min.js:272
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3`

**Comment by harigyan** [comment]
@MishraAarambh 

There is no error in sever console. 
should I configure anything after taking pull.

**Comment by harigyan** [comment]
Change in Add item Form : 
1. Add 'Price' field to set the rate/price of the item during adding into system. 
2. Order of fields should be : 
- Item Code
- Item Price
- Name 
- Description

Change in List of Items table : 
1. Remove RateCode column from the table. 
2. It should be used by system internally. 
3. Any where we need to show the rate/price use 'Item Price' as label or column heading.

**Comment by harigyan** [comment]
@MishraAarambh 

Please see above comment and implement. 
itemCode field is mapped with wrong field (rateCode) of database. Please correct it.  rateCode should not be a column in database,class field etc. 
You can use ItemRateCode.getItemRateCode() and ItemRateCode.getItemPrice() to compute relation in rateCode and price of item.
