### ISSUE TITLE
Customer Management 

### ISSUE THREAD

**Issue by harigyan** [MishraAarambh/mahalaxmi#3]
To manage customers of company implement following steps : 

Menu Options required in header are : 

- Add Customer
- Find Customer

Add Customer
--------------------
User should be able to add customer information into the system. Fields required are : 
- Customer Name
- Mobile
- Email
- Street Address
- City 
- State
- Country
- Pin

Additional table columns for database are : 
- customerId [auto increment]
- addedOn [current timestamp]
- addedBy [current user]

Find Customer or List customers 
------------------------------------
A form to search customer by name,mobile,email or address in top of page. A list of records in following format required. 

S. NO. | Customer Name | Mobile | Email | Address | Added On | Added By | Links |
-------|------------------|--------|------|----------|-----------|-----------|-----|

Pagination should be provided.

**Comment by MishraAarambh** [comment]
written the services for adding the customer

have to write the services for listing the customers and to search them

**Comment by harigyan** [comment]
@MishraAarambh 

Add Customer task working fine. 
Mandatory fields are : 
- Customer Name 
- Mobile

Please remove 'required' from all other fields and make optional.
