### ISSUE TITLE
Challan Management

### ISSUE THREAD

**Issue by harigyan** [MishraAarambh/mahalaxmi#5]
Challan management facility in system will allow users to add,edit and list challans. 

Add Challan
-------------
User should be able to add new challan in the system. A challan will be partitioned in three parts:
1. Customer Information
2. Challan Info
3. Items on Challan. 
To store the challan information into database we need two tables challan and challanItem with one to many relationship (foreign key constraint). 

## challan table:
--------------
branchCode
fy [Financial Year]
challanNo [auto Increment]
customerId
addedOn [current timestamp]
addedBy [current user]
discount 
otherCharges [if any] optional

## challanItem table
---------------------
branchCode
fy 
challan no
itemCode
quantity
price  [it may be numeric value or in rateCode format i.e. VINOD KUMAR]

How to create Challan ? 
---------------------------
1. Goto to Create Challan option. 
2. Select customer information. [if exists in system.] If not exists than use link to add 'Add Customer'].  You may show dialog to select or add customer. 
3. Enter details of challan like discount or other charges. 
4. Items List
    A. User should be able to add items in challan.
    B. user should be able to remove items from the challan. 
5. Save Challan. 

Print Challan
--------------------
User should be able to print challan with following settings. 
1. print on A4 paper in landscape orientation.
2. print two copies at a time. 
    (a) Original Challan
    (b) Duplication Challan
3. User should be able to print old challans. 

List Challans 
------------------
User should be  able to list/find challans. Various reports/filter options may be provided to view challans. 
=> User should be able to print list of challans on a specific date.

**Comment by MishraAarambh** [comment]
java services for adding a challan are ready
need to wire the angular part and send data from client to the server
