### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by harigyan** [MishraAarambh/mahalaxmi#6]
@MishraAarambh 

When logged in with hari.gyan.12345@gmail.com user, dialogs no displayed on clicking button, but using aarambh2812@gmail.com it show all dialogs. 

Please check and resolve

**Comment by MishraAarambh** [comment]
Hi @harigyan  sir,
I've made some recent commits and this should get resolved within those.
No specific user permissions given to any user. Roles for every user are same.
